export const rows = [
  {
    id: 1,
    name: "Rachid Bigharassne",
    email: "rachidbigharassne@gmail.com",
    age: 21,
    phone: "(+212)688-637343",
    address: "3118 Hay Taddar Anza Agadir",
    city: "Agadir",
    zipCode: 80000,
    CIN: "J588828",
  },
  {
    id: 2,
    name: "Omar Benhaddou",
    email: "omar.benhaddou@example.com",
    age: 29,
    phone: "(+212)667-890123",
    address: "Lotissement Ennakhil, Hay Nahda",
    city: "Rabat",
    zipCode: 10090,
    CIN: "B723456",
  },
  {
    id: 3,
    name: "Aicha Rami",
    email: "aicha.rami@example.com",
    age: 26,
    phone: "(+212)663-556677",
    address: "Avenue Moulay Ismail, Bloc 8",
    city: "Fes",
    zipCode: 30000,
    CIN: "F834501",
  },
  {
    id: 4,
    name: "Khalid Meknassi",
    email: "khalid.meknassi@example.com",
    age: 31,
    phone: "(+212)668-987654",
    address: "10 Rue Ibn Sina, Hay Salam",
    city: "Agadir",
    zipCode: 80000,
    CIN: "A110328",
  },
  {
    id: 5,
    name: "Sofia Lamrani",
    email: "sofia.lamrani@example.com",
    age: 28,
    phone: "(+212)660-334455",
    address: "Rue Al Wahda, Imm 14, Appt 5",
    city: "Marrakech",
    zipCode: 40000,
    CIN: "M553890",
  },
  {
    id: 6,
    name: "Youssef Chafik",
    email: "youssef.chafik@example.com",
    age: 30,
    phone: "(+212)672-334411",
    address: "34 Avenue des FAR, Hay Al Qods",
    city: "Oujda",
    zipCode: 60000,
    CIN: "O334562",
  },
  {
    id: 7,
    name: "Noura El Amrani",
    email: "noura.elamrani@example.com",
    age: 25,
    phone: "(+212)675-778899",
    address: "Résidence Al Ikram, Imm 9",
    city: "Tanger",
    zipCode: 90000,
    CIN: "T884920",
  },
  {
    id: 8,
    name: "Hamza Bouzidi",
    email: "hamza.bouzidi@example.com",
    age: 27,
    phone: "(+212)670-123987",
    address: "Bd Zerktouni, Rés. Atlas, Appt 3",
    city: "Meknes",
    zipCode: 50000,
    CIN: "H623791",
  },
  {
    id: 9,
    name: "Imane Farissi",
    email: "imane.farissi@example.com",
    age: 22,
    phone: "(+212)673-445566",
    address: "Rue Ibn Tofail, Hay Al Amal",
    city: "El Jadida",
    zipCode: 24000,
    CIN: "E219438",
  },
];

export const columns = [
  {
    field: "id",
    headerName: "ID",
    flex: 0.5,
  },
  {
    field: "name",
    headerName: "Name",
    flex: 1,
  },
  {
    field: "email",
    headerName: "Email",
    flex: 1.5,
  },
  {
    field: "age",
    headerName: "Age",
    type: "number",
    flex: 0.5,
  },

  {
    field: "phone",
    headerName: "Phone Number",
    flex: 1,
  },
  {
    field: "address",
    headerName: "Address",
    flex: 2,
  },
  {
    field: "city",
    headerName: "City",
    flex: 1,
  },
  {
    field: "zipCode",
    headerName: "Zip Code",
    flex: 0.7,
  },
  {
    field: "CIN",
    headerName: "CIN",
    flex: 0.8,
  },
];
